version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "eventsourcingpattern"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-tvxt83bsk97"
s3_prefix = "eventsourcingpattern"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
